// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract WorkorderManager {
    struct Workorder {
        string workorderId;
        string roadId;
        string timestamp; // Store as ISO string for simplicity, could use uint for block timestamp
        string status; // e.g., "active", "completed"
        string roadName;
        address createdBy;
        uint blockTimestamp;
    }

    mapping(string => Workorder) public workorders; // workorderId => Workorder details
    string[] public workorderIds; // Keep track of all created IDs

    event WorkorderCreated(
        string indexed workorderId,
        string indexed roadId,
        address createdBy,
        uint blockTimestamp
    );

    address public owner;

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can call this function");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /**
     * @notice Creates a new workorder and stores it on the blockchain.
     * @param _workorderId Unique ID generated by the backend.
     * @param _roadId ID of the road requiring maintenance.
     * @param _timestamp ISO timestamp string of when the order was generated.
     * @param _status Initial status (e.g., "active").
     * @param _roadName Name of the road.
     */
    function createWorkorder(
        string memory _workorderId,
        string memory _roadId,
        string memory _timestamp,
        string memory _status,
        string memory _roadName
    ) public {
        // Basic check to prevent overwriting (could add more complex checks)
        require(bytes(workorders[_workorderId].workorderId).length == 0, "Workorder ID already exists");

        workorders[_workorderId] = Workorder({
            workorderId: _workorderId,
            roadId: _roadId,
            timestamp: _timestamp,
            status: _status,
            roadName: _roadName,
            createdBy: msg.sender,
            blockTimestamp: block.timestamp
        });

        workorderIds.push(_workorderId);

        emit WorkorderCreated(_workorderId, _roadId, msg.sender, block.timestamp);
    }

    /**
     * @notice Retrieves details for a specific workorder.
     * @param _workorderId The ID of the workorder to retrieve.
     * @return Workorder struct containing all details.
     */
    function getWorkorder(string memory _workorderId) public view returns (Workorder memory) {
        require(bytes(workorders[_workorderId].workorderId).length != 0, "Workorder not found");
        return workorders[_workorderId];
    }

    /**
     * @notice Returns the total number of workorders created.
     */
    function getWorkorderCount() public view returns (uint) {
        return workorderIds.length;
    }

    // Optional: Function to update status (consider adding permissions)
    // function updateWorkorderStatus(string memory _workorderId, string memory _newStatus) public {
    //     require(bytes(workorders[_workorderId].workorderId).length != 0, "Workorder not found");
    //     // Add permission checks if needed (e.g., only owner or specific role)
    //     workorders[_workorderId].status = _newStatus;
    // }
}
